# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _example_iterator_02
else:
    import _example_iterator_02

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def getColor(ptr):
    return _example_iterator_02.getColor(ptr)
class Element(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _example_iterator_02.Element_swiginit(self, _example_iterator_02.new_Element(*args))
    __swig_destroy__ = _example_iterator_02.delete_Element

    def get(self):
        return _example_iterator_02.Element_get(self)

    def set(self, var):
        return _example_iterator_02.Element_set(self, var)

# Register Element in _example_iterator_02:
_example_iterator_02.Element_swigregister(Element)

class Collection(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _example_iterator_02.Collection_swiginit(self, _example_iterator_02.new_Collection())
    __swig_destroy__ = _example_iterator_02.delete_Collection

    def add(self, element):
        return _example_iterator_02.Collection_add(self, element)

    def begin(self, *args):
        return _example_iterator_02.Collection_begin(self, *args)

    def end(self, *args):
        return _example_iterator_02.Collection_end(self, *args)

    def __iter__(self):
        return _example_iterator_02.Collection___iter__(self)

# Register Collection in _example_iterator_02:
_example_iterator_02.Collection_swigregister(Collection)

class CollectionIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, col):
        _example_iterator_02.CollectionIterator_swiginit(self, _example_iterator_02.new_CollectionIterator(col))
    __swig_destroy__ = _example_iterator_02.delete_CollectionIterator

    def hasMoreElements(self):
        return _example_iterator_02.CollectionIterator_hasMoreElements(self)

    def next(self):
        return _example_iterator_02.CollectionIterator_next(self)

    def peekNext(self):
        return _example_iterator_02.CollectionIterator_peekNext(self)

    def __next__(self):
        return _example_iterator_02.CollectionIterator___next__(self)

# Register CollectionIterator in _example_iterator_02:
_example_iterator_02.CollectionIterator_swigregister(CollectionIterator)



